const BASE_URL = "https://ik.imagekit.io/fl2lbswwo/vladsazon-blog";

export const PHOTOS_METADATA = [
  {
    src: `${BASE_URL}/warsaw-june-2021-park.webp`,
    width: 960,
    height: 1280,
    alt: "Calm lake in a park reflecting green trees under an overcast sky.",
    location: "Warsaw, Poland",
    date: "June, 2021",
  },
  {
    src: `${BASE_URL}/lisbon-nov-2021-ferry.webp`,
    width: 960,
    height: 1280,
    alt: "View from a ferry window of three sailboats on calm blue water at golden hour.",
    location: "Lisbon, Portugal",
    date: "November, 2021",
  },
  {
    src: `${BASE_URL}/porto-nov-2021-beach.webp`,
    width: 960,
    height: 1280,
    alt: "Sandy beach with sea foam and waves, with a coastal city and construction cranes in the background.",
    location: "Porto, Portugal",
    date: "November, 2021",
  },
  {
    src: `${BASE_URL}/porto-nov-2021-bridge.webp`,
    width: 960,
    height: 1280,
    alt: "High-angle view of the Dom Luís I Bridge spanning the Douro River in Porto.",
    location: "Porto, Portugal",
    date: "November, 2021",
  },
  {
    src: `${BASE_URL}/porto-nov-2021-ceramic.webp`,
    width: 960,
    height: 1280,
    alt: "Ornate yellow ceramic tiles with a missing section revealing rough stone underneath.",
    location: "Porto, Portugal",
    date: "November, 2021",
  },
  {
    src: `${BASE_URL}/porto-nov-2021-ocean.webp`,
    width: 960,
    height: 1280,
    alt: "Close-up of white bubbly sea foam washing over golden-brown sandy beach.",
    location: "Porto, Portugal",
    date: "November, 2021",
  },
  {
    src: `${BASE_URL}/porto-nov-2021-pier.webp`,
    width: 960,
    height: 1280,
    alt: "Stone lighthouse on a breakwater with crashing waves and a coastal city behind.",
    location: "Porto, Portugal",
    date: "November, 2021",
  },
  {
    src: `${BASE_URL}/porto-nov-2021-res.webp`,
    width: 960,
    height: 1280,
    alt: "Seaside restaurant terrace at sunset with modern chairs overlooking the ocean.",
    location: "Porto, Portugal",
    date: "November, 2021",
  },
  {
    src: `${BASE_URL}/porto-nov-2021-sand.webp`,
    width: 960,
    height: 1280,
    alt: "Close-up of smooth multicolored pebbles covering a beach.",
    location: "Porto, Portugal",
    date: "November, 2021",
  },
  {
    src: `${BASE_URL}/porto-nov-2021-tel.webp`,
    width: 960,
    height: 1280,
    alt: "A weathered public telephone hood with a corded landline phone on a city street at night.",
    location: "Porto, Portugal",
    date: "November, 2021",
  },
  {
    src: `${BASE_URL}/porto-nov-2021-1.webp`,
    width: 960,
    height: 1280,
    alt: "Wide sandy beach with scattered rocks and gentle waves at golden hour, with a distant lighthouse.",
    location: "Porto, Portugal",
    date: "November, 2021",
  },
  {
    src: `${BASE_URL}/warsaw-april-2022-cathedral.webp`,
    width: 960,
    height: 1280,
    alt: "Large gold chandelier with crystal pendants hanging in a white Baroque cathedral interior.",
    location: "Warsaw, Poland",
    date: "April, 2022",
  },
  {
    src: `${BASE_URL}/gdansk-june-2022-park-oliwski-2.webp`,
    width: 960,
    height: 1280,
    alt: "Looking up through a dense green tree canopy framing a bright overcast sky.",
    location: "Gdańsk, Poland",
    date: "June, 2022",
  },
  {
    src: `${BASE_URL}/gdansk-june-2022-park-oliwski-3.webp`,
    width: 960,
    height: 1280,
    alt: "A straight canal bordered by tall manicured hedges in a formal garden.",
    location: "Gdańsk, Poland",
    date: "June, 2022",
  },
  {
    src: `${BASE_URL}/gdansk-june-2022-park-oliwski.webp`,
    width: 960,
    height: 1280,
    alt: "Upward view through a linden tree canopy of green heart-shaped leaves and tangled branches.",
    location: "Gdańsk, Poland",
    date: "June, 2022",
  },
  {
    src: `${BASE_URL}/warsaw-june-2022-park.webp`,
    width: 960,
    height: 1280,
    alt: "Sunny park lake surrounded by lush green trees with reflections on calm water.",
    location: "Warsaw, Poland",
    date: "June, 2022",
  },
  {
    src: `${BASE_URL}/warsaw-oct-2022-sunset-2.webp`,
    width: 960,
    height: 1280,
    alt: "Fiery orange and pink sunset clouds over a city street with apartment buildings.",
    location: "Warsaw, Poland",
    date: "October, 2022",
  },
  {
    src: `${BASE_URL}/warsaw-oct-2022-sunset.webp`,
    width: 960,
    height: 1280,
    alt: "Vibrant orange and purple sunset over silhouetted trees and apartment buildings.",
    location: "Warsaw, Poland",
    date: "October, 2022",
  },
  {
    src: `${BASE_URL}/warsaw-may-2023-park.webp`,
    width: 960,
    height: 1280,
    alt: "Abstract stone sculpture of two embracing figures in a green forest clearing.",
    location: "Warsaw, Poland",
    date: "May, 2023",
  },
  {
    src: `${BASE_URL}/warsaw-may-2023-zoo.webp`,
    width: 960,
    height: 1280,
    alt: "Zoo entrance at sunset with ticket booths silhouetted against an orange and pink sky.",
    location: "Warsaw, Poland",
    date: "May, 2023",
  },
  {
    src: `${BASE_URL}/sopot-july-2023-apt.webp`,
    width: 960,
    height: 1280,
    alt: "Mid-century modern living room with wooden bookshelves, TV console, and patterned rug.",
    location: "Sopot, Poland",
    date: "July, 2023",
  },
  {
    src: `${BASE_URL}/sopot-july-2023-park.webp`,
    width: 960,
    height: 1280,
    alt: "Wooden boardwalk path leading through a lush green forest with sunlight filtering through.",
    location: "Sopot, Poland",
    date: "July, 2023",
  },
  {
    src: `${BASE_URL}/barcelona-jan-2024-sculpt.webp`,
    width: 960,
    height: 1280,
    alt: "Bronze sculpture of five kneeling and standing figures beneath a stone angel relief in a Barcelona archway.",
    location: "Barcelona, Spain",
    date: "January, 2024",
  },
  {
    src: `${BASE_URL}/kemer-may-2024-hotel.webp`,
    width: 960,
    height: 1280,
    alt: "Resort swimming pools and empty patio seating under a dark overcast sky with misty mountains.",
    location: "Kemer, Turkey",
    date: "May, 2024",
  },
  {
    src: `${BASE_URL}/kemer-oct-2024-sea-2.webp`,
    width: 960,
    height: 1280,
    alt: "Turquoise water with shimmering light patterns revealing smooth pebbles on the seabed under a cloudless blue sky.",
    location: "Kemer, Turkey",
    date: "October, 2024",
  },
  {
    src: `${BASE_URL}/warsaw-dec-2024-wine.webp`,
    width: 960,
    height: 1280,
    alt: "Close-up of a glass of red wine casting a glowing red reflection on a white tablecloth.",
    location: "Warsaw, Poland",
    date: "December, 2024",
  },
  {
    src: `${BASE_URL}/wroclaw-dec-2024-bike.webp`,
    width: 960,
    height: 1280,
    alt: "Bronze dwarf gnome sculpture riding a motorcycle and making a peace sign.",
    location: "Wrocław, Poland",
    date: "December, 2024",
  },
  {
    src: `${BASE_URL}/istanbul-nov-2024-ferry.webp`,
    width: 960,
    height: 1280,
    alt: "View from a ferry stern of a churning wake, seagulls flying, and the Istanbul skyline with minarets under an overcast sky.",
    location: "Istanbul, Turkey",
    date: "November, 2024",
  },
  {
    src: `${BASE_URL}/budapest-feb-2025-cathedral.webp`,
    width: 960,
    height: 1280,
    alt: "Low-angle view of a gilded cathedral dome with frescoes, statues, and arched windows.",
    location: "Budapest, Hungary",
    date: "February, 2025",
  },
  {
    src: `${BASE_URL}/benalmadena-oct-2025-hotel.webp`,
    width: 960,
    height: 1280,
    alt: "Modern hotel lounge with wicker furniture and hanging egg chairs overlooking the Mediterranean Sea.",
    location: "Benalmádena, Spain",
    date: "October, 2025",
  },
  {
    src: `${BASE_URL}/benalmadena-oct-2025-hotel-2.webp`,
    width: 960,
    height: 1280,
    alt: "Street at dusk framed by tall palm trees, with a sunset sky fading from deep blue to orange and lit streetlamps.",
    location: "Benalmádena, Spain",
    date: "October, 2025",
  },
  {
    src: `${BASE_URL}/benalmadena-oct-2025-sea.webp`,
    width: 960,
    height: 1280,
    alt: "High-angle view of a sunny beach with grey thatched umbrellas, white loungers, and a stone jetty curving into the blue sea.",
    location: "Benalmádena, Spain",
    date: "October, 2025",
  },
  {
    src: `${BASE_URL}/benalmadena-oct-2025-sea-view.webp`,
    width: 960,
    height: 1280,
    alt: "High-angle view of a sandy beach with palm trees, a paved promenade, and calm blue sea under a clear sky.",
    location: "Benalmádena, Spain",
    date: "October, 2025",
  },
  {
    src: `${BASE_URL}/istanbul-nov-2025-cat-2.webp`,
    width: 960,
    height: 1280,
    alt: "Animal paw prints pressed into wet grey stone pavement tiles.",
    location: "Istanbul, Turkey",
    date: "November, 2025",
  },
  {
    src: `${BASE_URL}/istanbul-nov-2025-cat.webp`,
    width: 960,
    height: 1280,
    alt: "A black cat sleeping curled up on the seat of a red motor scooter.",
    location: "Istanbul, Turkey",
    date: "November, 2025",
  },
  {
    src: `${BASE_URL}/kemer-nov-2025-sea-2.webp`,
    width: 960,
    height: 1280,
    alt: "Pebble beach at dusk with calm waves, distant mountains, and a dramatic cloudy sky.",
    location: "Kemer, Turkey",
    date: "November, 2025",
  },
  {
    src: `${BASE_URL}/kemer-nov-2025-sea.webp`,
    width: 960,
    height: 1280,
    alt: "Turquoise sea waves with white foam washing onto a dark pebble beach under a blue sky.",
    location: "Kemer, Turkey",
    date: "November, 2025",
  },
  {
    src: `${BASE_URL}/kemer-nov-2025-sunset.webp`,
    width: 960,
    height: 1280,
    alt: "Vibrant orange sunset over a coastal city with mountains, palm trees, and parked cars.",
    location: "Kemer, Turkey",
    date: "November, 2025",
  },
  {
    src: `${BASE_URL}/rome-dec-2025-colos-2.webp`,
    width: 960,
    height: 1280,
    alt: "Low-angle view of the Colosseum's weathered stone arches and statues under a clear blue sky.",
    location: "Rome, Italy",
    date: "December, 2025",
  },
  {
    src: `${BASE_URL}/rome-dec-2025-colos.webp`,
    width: 960,
    height: 1280,
    alt: "Wide view of the Colosseum at golden hour with the Arch of Constantine and tourists below.",
    location: "Rome, Italy",
    date: "December, 2025",
  },
  {
    src: `${BASE_URL}/rome-dec-2025-magazines.webp`,
    width: 960,
    height: 1280,
    alt: "Italian newsstand display with magazines on AI and history, and 2026 animal calendars.",
    location: "Rome, Italy",
    date: "December, 2025",
  },
  {
    src: `${BASE_URL}/rome-dec-2025-park-2.webp`,
    width: 960,
    height: 1280,
    alt: "Low-angle view of a tall stone pine with an umbrella-shaped canopy against a clear blue sky.",
    location: "Rome, Italy",
    date: "December, 2025",
  },
  {
    src: `${BASE_URL}/rome-dec-2025-park.webp`,
    width: 960,
    height: 1280,
    alt: "Headless classical stone statue on an ornate pedestal in a tree-lined park.",
    location: "Rome, Italy",
    date: "December, 2025",
  },
  {
    src: `${BASE_URL}/rome-dec-2025-pasta.webp`,
    width: 960,
    height: 1280,
    alt: "Close-up of rigatoni pasta in creamy tomato sauce topped with grated cheese in a white bowl.",
    location: "Rome, Italy",
    date: "December, 2025",
  },
  {
    src: `${BASE_URL}/rome-dec-2025-street.webp`,
    width: 960,
    height: 1280,
    alt: "Wide tree-lined city street with autumn foliage and European apartment buildings.",
    location: "Rome, Italy",
    date: "December, 2025",
  },
  {
    src: `${BASE_URL}/warsaw-jan-2026-christmas.webp`,
    width: 960,
    height: 1280,
    alt: "Large illuminated Christmas tree with red ornaments and a golden star between brick and glass buildings.",
    location: "Warsaw, Poland",
    date: "January, 2026",
  },
] as const satisfies {
  src: string;
  width: number;
  height: number;
  alt: string;
  location: string;
  date: string;
}[];
